services:
  - type: web
    name: neru-ttc-chatgpt-bot
    runtime: node
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        value: <your-openai-api-key>
      - key: CHANNELS
        value: SharpNip
      - key: GPT_MODE
        value: "CHAT"
      - key: HISTORY_LENGTH
        value: "5"
      - key: MODEL_NAME
        value: "gpt-3.5-turbo"
      - key: COMMAND_NAME
        value: ""
      - key: SEND_USERNAME
        value: "true"
      - key: ENABLE_TTS
        value: "true"
      - key: ENABLE_CHANNEL_POINTS
        value: "false"
      - key: COOLDOWN_DURATION
        value: "10"
